In [2]:
# Importing modules
import torch
import numpy as np
import pandas as pd
import torch.nn as nn
from sklearn.neighbors import NearestNeighbors
from sklearn.preprocessing import StandardScaler
from sklearn.metrics.pairwise import cosine_similarity

In [3]:
# Loading dataset
df = pd.read_csv('../dataset/dataset1.csv')
df.drop(columns=['Unnamed: 0'], inplace=True)
df

,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
0,5SuOikwiRyPMVoIQDJUgSV,Gen Hoshino,Comedy,Comedy,73,230666,False,0.676,0.4610,1,-6.746,0,0.1430,0.0322,0.000001,0.3580,0.7150,87.917,4,acoustic
1,4qPNDBW1i3p13qLCt0Ki3A,Ben Woodward,Ghost (Acoustic),Ghost - Acoustic,55,149610,False,0.420,0.1660,1,-17.235,1,0.0763,0.9240,0.000006,0.1010,0.2670,77.489,4,acoustic
2,1iJBSr7s7jYXzM8EGcbK5b,Ingrid Michaelson;ZAYN,To Begin Again,To Begin Again,57,210826,False,0.438,0.3590,0,-9.734,1,0.0557,0.2100,0.000000,0.1170,0.1200,76.332,4,acoustic
3,6lfxq3CG4xtTiEg7opyCyx,Kina Grannis,Crazy Rich Asians (Original Motion Picture Sou...,Can't Help Falling In Love,71,201933,False,0.266,0.0596,0,-18.515,1,0.0363,0.9050,0.000071,0.1320,0.1430,181.740,3,acoustic
4,5vjLSffimiIP26QG5WcN2K,Chord Overstreet,Hold On,Hold On,82,198853,False,0.618,0.4430,2,-9.681,1,0.0526,0.4690,0.000000,0.0829,0.1670,119.949,4,acoustic
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
113995,2C3TZjDRiAzdyViavDJ217,Rainy Lullaby,#mindfulness - Soft Rain for Mindful Meditatio...,Sleep My Little Boy,21,384999,False,0.172,0.2350,5,-16.393,1,0.0422,0.6400,0.928000,0.0863,0.0339,125.995,5,world-music
113996,1hIz5L4IB9hN3WRYPOCGPw,Rainy Lullaby,#mindfulness - Soft Rain for Mindful Meditatio...,Water Into Light,22,385000,False,0.174,0.1170,0,-18.318,0,0.0401,0.9940,0.976000,0.1050,0.0350,85.239,4,world-music
113997,6x8ZfSoqDjuNa5SVP5QjvX,Cesária Evora,Best Of,Miss Perfumado,22,271466,False,0.629,0.3290,0,-10.895,0,0.0420,0.8670,0.000000,0.0839,0.7430,132.378,4,world-music
113998,2e6sXL2bYv4bSz6VTdnfLs,Michael W. Smith,Change Your World,Friends,41,283893,False,0.587,0.5060,7,-10.889,1,0.0297,0.3810,0.000000,0.2700,0.4130,135.960,4,world-music
113999,2hETkH7cOfqmz3LqZDHZf5,Cesária Evora,Miss Perfumado,Barbincor,22,241826,False,0.526,0.4870,1,-10.204,0,0.0725,0.6810,0.000000,0.0893,0.7080,79.198,4,world-music

In [4]:
# Empty rows dropped
df.info()
df.dropna(inplace=True)
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 114000 entries, 0 to 113999
Data columns (total 20 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   track_id          114000 non-null  object
 1   artists           113999 non-null  object
 2   album_name        113999 non-null  object
 3   track_name        113999 non-null  object
 4   popularity        114000 non-null  int64
 5   duration_ms       114000 non-null  int64
 6   explicit          114000 non-null  bool
 7   danceability      114000 non-null  float64
 8   energy            114000 non-null  float64
 9   key               114000 non-null  int64
 10  loudness          114000 non-null  float64
 11  mode              114000 non-null  int64
 12  speechiness       114000 non-null  float64
 13  acousticness      114000 non-null  float64
 14  instrumentalness  114000 non-null  float64
 15  liveness          114000 non-null  float64
 16  valence           114000 non-null  float64
 17  tempo             114000 non-null  float64
 18  time_signature    114000 non-null  int64
 19  track_genre       114000 non-null  object
dtypes: bool(1), float64(9), int64(5), object(5)
memory usage: 16.6+ MB

track_id            0
artists             0
album_name          0
track_name          0
popularity          0
duration_ms         0
explicit            0
danceability        0
energy              0
key                 0
loudness            0
mode                0
speechiness         0
acousticness        0
instrumentalness    0
liveness            0
valence             0
tempo               0
time_signature      0
track_genre         0
dtype: int64

In [5]:
# Data cleaning
df.columns = df.columns.str.upper()
df['EXPLICIT'] = df['EXPLICIT'].astype(int)
df['DURATION_MIN'] = df['DURATION_MS'] / 60000
df.drop_duplicates(subset=['TRACK_ID'], inplace=True)
df.drop_duplicates(subset=['TRACK_NAME'], inplace=True)
df.reset_index(drop=True, inplace=True)
df

,TRACK_ID,ARTISTS,ALBUM_NAME,TRACK_NAME,POPULARITY,DURATION_MS,EXPLICIT,DANCEABILITY,ENERGY,KEY,...,MODE,SPEECHINESS,ACOUSTICNESS,INSTRUMENTALNESS,LIVENESS,VALENCE,TEMPO,TIME_SIGNATURE,TRACK_GENRE,DURATION_MIN
0,5SuOikwiRyPMVoIQDJUgSV,Gen Hoshino,Comedy,Comedy,73,230666,0,0.676,0.4610,1,...,0,0.1430,0.0322,0.000001,0.3580,0.7150,87.917,4,acoustic,3.844433
1,4qPNDBW1i3p13qLCt0Ki3A,Ben Woodward,Ghost (Acoustic),Ghost - Acoustic,55,149610,0,0.420,0.1660,1,...,1,0.0763,0.9240,0.000006,0.1010,0.2670,77.489,4,acoustic,2.493500
2,1iJBSr7s7jYXzM8EGcbK5b,Ingrid Michaelson;ZAYN,To Begin Again,To Begin Again,57,210826,0,0.438,0.3590,0,...,1,0.0557,0.2100,0.000000,0.1170,0.1200,76.332,4,acoustic,3.513767
3,6lfxq3CG4xtTiEg7opyCyx,Kina Grannis,Crazy Rich Asians (Original Motion Picture Sou...,Can't Help Falling In Love,71,201933,0,0.266,0.0596,0,...,1,0.0363,0.9050,0.000071,0.1320,0.1430,181.740,3,acoustic,3.365550
4,5vjLSffimiIP26QG5WcN2K,Chord Overstreet,Hold On,Hold On,82,198853,0,0.618,0.4430,2,...,1,0.0526,0.4690,0.000000,0.0829,0.1670,119.949,4,acoustic,3.314217
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
73603,4WbOUe6T0sozC7z5ZJgiAA,Lucas Cervetti,Frecuencias Álmicas en 432hz,"Frecuencia Álmica, Pt. 4",22,305454,0,0.331,0.1710,1,...,1,0.0350,0.9200,0.022900,0.0679,0.3270,132.147,3,world-music,5.090900
73604,2C3TZjDRiAzdyViavDJ217,Rainy Lullaby,#mindfulness - Soft Rain for Mindful Meditatio...,Sleep My Little Boy,21,384999,0,0.172,0.2350,5,...,1,0.0422,0.6400,0.928000,0.0863,0.0339,125.995,5,world-music,6.416650
73605,1hIz5L4IB9hN3WRYPOCGPw,Rainy Lullaby,#mindfulness - Soft Rain for Mindful Meditatio...,Water Into Light,22,385000,0,0.174,0.1170,0,...,0,0.0401,0.9940,0.976000,0.1050,0.0350,85.239,4,world-music,6.416667
73606,6x8ZfSoqDjuNa5SVP5QjvX,Cesária Evora,Best Of,Miss Perfumado,22,271466,0,0.629,0.3290,0,...,0,0.0420,0.8670,0.000000,0.0839,0.7430,132.378,4,world-music,4.524433
73607,2hETkH7cOfqmz3LqZDHZf5,Cesária Evora,Miss Perfumado,Barbincor,22,241826,0,0.526,0.4870,1,...,0,0.0725,0.6810,0.000000,0.0893,0.7080,79.198,4,world-music,4.030433

In [6]:
# Features & weight selection
features = [
    'DANCEABILITY', 'ENERGY', 'LOUDNESS', 'SPEECHINESS',
    'ACOUSTICNESS', 'INSTRUMENTALNESS', 'LIVENESS',
    'VALENCE', 'TEMPO'
]
weights = np.array([1.2, 1.5, 0.8, 1.0, 1.0, 1.0, 1.0, 1.3, 0.7])

In [7]:
# Scaling features
scaler = StandardScaler()
scaled_features = scaler.fit_transform(df[features]) * weights
scaled_features

array([[ 0.78863374, -1.02023105,  0.27944933, ...,  0.67221997,
         1.21981316, -0.79412371],
       [-0.93226725, -2.73081989, -1.29792513, ..., -0.60454765,
        -0.98567917, -1.03607105],
       [-0.8112664 , -1.61168889, -0.16989712, ..., -0.52506017,
        -1.70935634, -1.06291542],
       ...,
       [-2.58594554, -3.0149516 , -1.46079066, ..., -0.58467578,
        -2.12780912, -0.85625786],
       [ 0.47268707, -1.78564707, -0.34449257, ..., -0.68949989,
         1.35765643,  0.23744713],
       [-0.21970669, -0.86946728, -0.24057745, ..., -0.66267287,
         1.18535234, -0.99641934]])

In [8]:
# Model defining
# model = NearestNeighbors(metric='cosine', algorithm='brute')
# model.fit(scaled_features)

In [9]:
# Testing
# distances, indices = model.kneighbors([scaled_features[34983]], n_neighbors=5)
# print(distances)
# print(indices)
# x = df.index[df['TRACK_NAME'] == 'Stairway to Heaven - Remaster']
# print(x)
# df.iloc[x]
# df.iloc[indices[0]]

In [10]:
# Converting scaled features to tensor
scaled_features_tensor = torch.tensor(scaled_features, dtype=torch.float32)
scaled_features_tensor

tensor([[ 0.7886, -1.0202,  0.2794,  ...,  0.6722,  1.2198, -0.7941],
        [-0.9323, -2.7308, -1.2979,  ..., -0.6045, -0.9857, -1.0361],
        [-0.8113, -1.6117, -0.1699,  ..., -0.5251, -1.7094, -1.0629],
        ...,
        [-2.5859, -3.0150, -1.4608,  ..., -0.5847, -2.1278, -0.8563],
        [ 0.4727, -1.7856, -0.3445,  ..., -0.6895,  1.3577,  0.2374],
        [-0.2197, -0.8695, -0.2406,  ..., -0.6627,  1.1854, -0.9964]])

In [11]:
#AutoEncoder
class AutoEncoder(nn.Module):
    def __init__(self):
        super().__init__()
        self.encoder = nn.Sequential(nn.Linear(9, 6), nn.ReLU(), nn.Linear(6, 4))
        self.decoder = nn.Sequential(nn.Linear(4, 6), nn.ReLU(), nn.Linear(6, 9))

    def forward(self, x):
        embedding = self.encoder(x)
        output = self.decoder(embedding)
        return embedding, output

In [12]:
#Initialize Model,Loss,Optimizer
model = AutoEncoder()

criterion = nn.MSELoss()   # Reconstruction loss
optimizer = torch.optim.Adam(model.parameters(), lr=0.001)

In [13]:
#Training Loop(Training the model so it learns embeddings)
epochs = 100
batch_size = 256

dataset = torch.utils.data.TensorDataset(scaled_features_tensor)
loader = torch.utils.data.DataLoader(dataset, batch_size=batch_size, shuffle=True)

for epoch in range(epochs):
    total_loss = 0
    
    for batch in loader:
        x = batch[0]
        
        embedding, output = model(x)
        loss = criterion(output, x)
        
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        
        total_loss += loss.item()
    
    avg_loss = total_loss / len(loader)
    print(f"Epoch {epoch+1}, Loss: {avg_loss:.4f}")

Epoch 1, Loss: 0.9599
Epoch 2, Loss: 0.4357
Epoch 3, Loss: 0.3054
Epoch 4, Loss: 0.2627
Epoch 5, Loss: 0.2380
Epoch 6, Loss: 0.2278
Epoch 7, Loss: 0.2217
Epoch 8, Loss: 0.2146
Epoch 9, Loss: 0.2063
Epoch 10, Loss: 0.1982
Epoch 11, Loss: 0.1923
Epoch 12, Loss: 0.1888
Epoch 13, Loss: 0.1868
Epoch 14, Loss: 0.1855
Epoch 15, Loss: 0.1847
Epoch 16, Loss: 0.1844
Epoch 17, Loss: 0.1843
Epoch 18, Loss: 0.1842
Epoch 19, Loss: 0.1841
Epoch 20, Loss: 0.1842
Epoch 21, Loss: 0.1840
Epoch 22, Loss: 0.1840
Epoch 23, Loss: 0.1840
Epoch 24, Loss: 0.1839
Epoch 25, Loss: 0.1838
Epoch 26, Loss: 0.1838
Epoch 27, Loss: 0.1839
Epoch 28, Loss: 0.1838
Epoch 29, Loss: 0.1838
Epoch 30, Loss: 0.1838
Epoch 31, Loss: 0.1838
Epoch 32, Loss: 0.1837
Epoch 33, Loss: 0.1837
Epoch 34, Loss: 0.1837
Epoch 35, Loss: 0.1837
Epoch 36, Loss: 0.1836
Epoch 37, Loss: 0.1837
Epoch 38, Loss: 0.1836
Epoch 39, Loss: 0.1837
Epoch 40, Loss: 0.1836
Epoch 41, Loss: 0.1835
Epoch 42, Loss: 0.1837
Epoch 43, Loss: 0.1837
Epoch 44, Loss: 0.1836
Epoch 45, Loss: 0.1836
Epoch 46, Loss: 0.1836
Epoch 47, Loss: 0.1835
Epoch 48, Loss: 0.1836
Epoch 49, Loss: 0.1836
Epoch 50, Loss: 0.1835
Epoch 51, Loss: 0.1835
Epoch 52, Loss: 0.1836
Epoch 53, Loss: 0.1835
Epoch 54, Loss: 0.1836
Epoch 55, Loss: 0.1835
Epoch 56, Loss: 0.1836
Epoch 57, Loss: 0.1835
Epoch 58, Loss: 0.1835
Epoch 59, Loss: 0.1835
Epoch 60, Loss: 0.1836
Epoch 61, Loss: 0.1835
Epoch 62, Loss: 0.1835
Epoch 63, Loss: 0.1835
Epoch 64, Loss: 0.1835
Epoch 65, Loss: 0.1836
Epoch 66, Loss: 0.1835
Epoch 67, Loss: 0.1835
Epoch 68, Loss: 0.1835
Epoch 69, Loss: 0.1834
Epoch 70, Loss: 0.1835
Epoch 71, Loss: 0.1834
Epoch 72, Loss: 0.1834
Epoch 73, Loss: 0.1836
Epoch 74, Loss: 0.1834
Epoch 75, Loss: 0.1834
Epoch 76, Loss: 0.1835
Epoch 77, Loss: 0.1836
Epoch 78, Loss: 0.1833
Epoch 79, Loss: 0.1834
Epoch 80, Loss: 0.1835
Epoch 81, Loss: 0.1835
Epoch 82, Loss: 0.1834
Epoch 83, Loss: 0.1835
Epoch 84, Loss: 0.1834
Epoch 85, Loss: 0.1834
Epoch 86, Loss: 0.1835
Epoch 87, Loss: 0.1835
Epoch 88, Loss: 0.1835
Epoch 89, Loss: 0.1833
Epoch 90, Loss: 0.1834
Epoch 91, Loss: 0.1835
Epoch 92, Loss: 0.1834
Epoch 93, Loss: 0.1835
Epoch 94, Loss: 0.1834
Epoch 95, Loss: 0.1834
Epoch 96, Loss: 0.1834
Epoch 97, Loss: 0.1835
Epoch 98, Loss: 0.1834
Epoch 99, Loss: 0.1834
Epoch 100, Loss: 0.1834

In [14]:
#Extract Embeddings
with torch.no_grad():
    embeddings, _ = model(scaled_features_tensor)

embeddings = embeddings.numpy()

In [15]:
# similarity_matrix = cosine_similarity(embeddings)

from sklearn.neighbors import NearestNeighbors

model = NearestNeighbors(metric='cosine', algorithm='brute')
model.fit(embeddings)

NearestNeighbors(algorithm='brute', metric='cosine')