In [71]:
import numpy as np
import pandas as pd
from sklearn.neighbors import NearestNeighbors
from sklearn.preprocessing import StandardScaler
from sklearn.metrics.pairwise import cosine_similarity

In [72]:
df = pd.read_csv('../dataset/dataset1.csv')
df.drop(columns=['Unnamed: 0'], inplace=True)
df

,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
0,5SuOikwiRyPMVoIQDJUgSV,Gen Hoshino,Comedy,Comedy,73,230666,False,0.676,0.4610,1,-6.746,0,0.1430,0.0322,0.000001,0.3580,0.7150,87.917,4,acoustic
1,4qPNDBW1i3p13qLCt0Ki3A,Ben Woodward,Ghost (Acoustic),Ghost - Acoustic,55,149610,False,0.420,0.1660,1,-17.235,1,0.0763,0.9240,0.000006,0.1010,0.2670,77.489,4,acoustic
2,1iJBSr7s7jYXzM8EGcbK5b,Ingrid Michaelson;ZAYN,To Begin Again,To Begin Again,57,210826,False,0.438,0.3590,0,-9.734,1,0.0557,0.2100,0.000000,0.1170,0.1200,76.332,4,acoustic
3,6lfxq3CG4xtTiEg7opyCyx,Kina Grannis,Crazy Rich Asians (Original Motion Picture Sou...,Can't Help Falling In Love,71,201933,False,0.266,0.0596,0,-18.515,1,0.0363,0.9050,0.000071,0.1320,0.1430,181.740,3,acoustic
4,5vjLSffimiIP26QG5WcN2K,Chord Overstreet,Hold On,Hold On,82,198853,False,0.618,0.4430,2,-9.681,1,0.0526,0.4690,0.000000,0.0829,0.1670,119.949,4,acoustic
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
113995,2C3TZjDRiAzdyViavDJ217,Rainy Lullaby,#mindfulness - Soft Rain for Mindful Meditatio...,Sleep My Little Boy,21,384999,False,0.172,0.2350,5,-16.393,1,0.0422,0.6400,0.928000,0.0863,0.0339,125.995,5,world-music
113996,1hIz5L4IB9hN3WRYPOCGPw,Rainy Lullaby,#mindfulness - Soft Rain for Mindful Meditatio...,Water Into Light,22,385000,False,0.174,0.1170,0,-18.318,0,0.0401,0.9940,0.976000,0.1050,0.0350,85.239,4,world-music
113997,6x8ZfSoqDjuNa5SVP5QjvX,Cesária Evora,Best Of,Miss Perfumado,22,271466,False,0.629,0.3290,0,-10.895,0,0.0420,0.8670,0.000000,0.0839,0.7430,132.378,4,world-music
113998,2e6sXL2bYv4bSz6VTdnfLs,Michael W. Smith,Change Your World,Friends,41,283893,False,0.587,0.5060,7,-10.889,1,0.0297,0.3810,0.000000,0.2700,0.4130,135.960,4,world-music
113999,2hETkH7cOfqmz3LqZDHZf5,Cesária Evora,Miss Perfumado,Barbincor,22,241826,False,0.526,0.4870,1,-10.204,0,0.0725,0.6810,0.000000,0.0893,0.7080,79.198,4,world-music

In [73]:
df.info()
df.dropna(inplace=True)
df.isnull().sum()

<class 'pandas.DataFrame'>
RangeIndex: 114000 entries, 0 to 113999
Data columns (total 20 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   track_id          114000 non-null  str
 1   artists           113999 non-null  str
 2   album_name        113999 non-null  str
 3   track_name        113999 non-null  str
 4   popularity        114000 non-null  int64
 5   duration_ms       114000 non-null  int64
 6   explicit          114000 non-null  bool
 7   danceability      114000 non-null  float64
 8   energy            114000 non-null  float64
 9   key               114000 non-null  int64
 10  loudness          114000 non-null  float64
 11  mode              114000 non-null  int64
 12  speechiness       114000 non-null  float64
 13  acousticness      114000 non-null  float64
 14  instrumentalness  114000 non-null  float64
 15  liveness          114000 non-null  float64
 16  valence           114000 non-null  float64
 17  tempo             114000 non-null  float64
 18  time_signature    114000 non-null  int64
 19  track_genre       114000 non-null  str
dtypes: bool(1), float64(9), int64(5), str(5)
memory usage: 16.6 MB

track_id            0
artists             0
album_name          0
track_name          0
popularity          0
duration_ms         0
explicit            0
danceability        0
energy              0
key                 0
loudness            0
mode                0
speechiness         0
acousticness        0
instrumentalness    0
liveness            0
valence             0
tempo               0
time_signature      0
track_genre         0
dtype: int64

In [74]:
df.columns = df.columns.str.upper()
df['EXPLICIT'] = df['EXPLICIT'].astype(int)  # True/False -> 1/0
df['DURATION_MIN'] = df['DURATION_MS'] / 60000
df.drop_duplicates(subset=['TRACK_ID'], inplace=True)
df

,TRACK_ID,ARTISTS,ALBUM_NAME,TRACK_NAME,POPULARITY,DURATION_MS,EXPLICIT,DANCEABILITY,ENERGY,KEY,...,MODE,SPEECHINESS,ACOUSTICNESS,INSTRUMENTALNESS,LIVENESS,VALENCE,TEMPO,TIME_SIGNATURE,TRACK_GENRE,DURATION_MIN
0,5SuOikwiRyPMVoIQDJUgSV,Gen Hoshino,Comedy,Comedy,73,230666,0,0.676,0.4610,1,...,0,0.1430,0.0322,0.000001,0.3580,0.7150,87.917,4,acoustic,3.844433
1,4qPNDBW1i3p13qLCt0Ki3A,Ben Woodward,Ghost (Acoustic),Ghost - Acoustic,55,149610,0,0.420,0.1660,1,...,1,0.0763,0.9240,0.000006,0.1010,0.2670,77.489,4,acoustic,2.493500
2,1iJBSr7s7jYXzM8EGcbK5b,Ingrid Michaelson;ZAYN,To Begin Again,To Begin Again,57,210826,0,0.438,0.3590,0,...,1,0.0557,0.2100,0.000000,0.1170,0.1200,76.332,4,acoustic,3.513767
3,6lfxq3CG4xtTiEg7opyCyx,Kina Grannis,Crazy Rich Asians (Original Motion Picture Sou...,Can't Help Falling In Love,71,201933,0,0.266,0.0596,0,...,1,0.0363,0.9050,0.000071,0.1320,0.1430,181.740,3,acoustic,3.365550
4,5vjLSffimiIP26QG5WcN2K,Chord Overstreet,Hold On,Hold On,82,198853,0,0.618,0.4430,2,...,1,0.0526,0.4690,0.000000,0.0829,0.1670,119.949,4,acoustic,3.314217
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
113995,2C3TZjDRiAzdyViavDJ217,Rainy Lullaby,#mindfulness - Soft Rain for Mindful Meditatio...,Sleep My Little Boy,21,384999,0,0.172,0.2350,5,...,1,0.0422,0.6400,0.928000,0.0863,0.0339,125.995,5,world-music,6.416650
113996,1hIz5L4IB9hN3WRYPOCGPw,Rainy Lullaby,#mindfulness - Soft Rain for Mindful Meditatio...,Water Into Light,22,385000,0,0.174,0.1170,0,...,0,0.0401,0.9940,0.976000,0.1050,0.0350,85.239,4,world-music,6.416667
113997,6x8ZfSoqDjuNa5SVP5QjvX,Cesária Evora,Best Of,Miss Perfumado,22,271466,0,0.629,0.3290,0,...,0,0.0420,0.8670,0.000000,0.0839,0.7430,132.378,4,world-music,4.524433
113998,2e6sXL2bYv4bSz6VTdnfLs,Michael W. Smith,Change Your World,Friends,41,283893,0,0.587,0.5060,7,...,1,0.0297,0.3810,0.000000,0.2700,0.4130,135.960,4,world-music,4.731550
113999,2hETkH7cOfqmz3LqZDHZf5,Cesária Evora,Miss Perfumado,Barbincor,22,241826,0,0.526,0.4870,1,...,0,0.0725,0.6810,0.000000,0.0893,0.7080,79.198,4,world-music,4.030433

In [75]:
features = [
    'DANCEABILITY', 'ENERGY', 'LOUDNESS', 'SPEECHINESS',
    'ACOUSTICNESS', 'INSTRUMENTALNESS', 'LIVENESS',
    'VALENCE', 'TEMPO'
]
weights = np.array([1.2, 1.5, 0.8, 1.0, 1.0, 1.0, 1.0, 1.3, 0.7])

In [76]:
scaler = StandardScaler()
scaled_features = scaler.fit_transform(df[features]) * weights
scaled_features

array([[ 0.773103  , -1.01396216,  0.26858146, ...,  0.72365633,
         1.21426125, -0.79351897],
       [-0.96552505, -2.73840279, -1.33846985, ..., -0.59507822,
        -1.00134935, -1.03588983],
       [-0.84327777, -1.61020943, -0.18921903, ..., -0.51297801,
        -1.72834658, -1.06278118],
       ...,
       [ 0.45390176, -1.78557627, -0.36709934, ..., -0.68282281,
         1.35273691,  0.23985756],
       [ 0.16865809, -0.75091189, -0.36618006, ...,  0.2721052 ,
        -0.27929768,  0.32311153],
       [-0.24562437, -0.86197756, -0.26122915, ..., -0.65511399,
         1.17964233, -0.99616871]], shape=(89740, 9))

In [77]:
model = NearestNeighbors(metric='cosine', algorithm='brute')
model.fit(scaled_features)

NearestNeighbors(algorithm='brute', metric='cosine')

In [78]:
distances, indices = model.kneighbors([scaled_features[34113]], n_neighbors=5)
print(distances)
print(indices)
df.iloc[indices[0]]

[[0.         0.02098922 0.02694881 0.03163268 0.03272658]]
[[34113 83573 34214 33854 32017]]

,TRACK_ID,ARTISTS,ALBUM_NAME,TRACK_NAME,POPULARITY,DURATION_MS,EXPLICIT,DANCEABILITY,ENERGY,KEY,...,MODE,SPEECHINESS,ACOUSTICNESS,INSTRUMENTALNESS,LIVENESS,VALENCE,TEMPO,TIME_SIGNATURE,TRACK_GENRE,DURATION_MIN
37835,6OfjeKC7ebVybVzBzkfAsz,Mc Th,Escola Proibida (Ao Vivo),Escola Proibida - Ao Vivo,43,162533,0,0.959,0.700,6,...,1,0.252,0.814,0.000000,0.1830,0.922,130.063,4,funk,2.708883
106365,2imjyIRZrtnPQFLOSTyJXF,Hov1,Barn av vår tid,Raindance,40,163239,1,0.942,0.676,2,...,1,0.212,0.750,0.000000,0.0852,0.801,122.025,4,swedish,2.720650
37948,4sbR19WEgjJUfRsU1z2DY2,Mikezin;Greezy,Suco de Fruta,Suco de Fruta,43,140487,1,0.852,0.745,3,...,0,0.221,0.772,0.000017,0.1160,0.779,123.038,4,funk,2.341450
37521,5P0jVJH9lPryyVX1pFqwXJ,Dj Viana;Dj Matheus Henrique,Barulho da cama,Barulho da cama,47,158769,0,0.888,0.731,5,...,0,0.288,0.558,0.000000,0.1130,0.887,130.068,4,funk,2.646150
35421,6ieHOekrCE2iCk4eLnfYQM,Bonde do gato preto;O Tubarão,São João do Gato Preto,Fala Meu Nome,41,169900,0,0.896,0.825,10,...,1,0.234,0.662,0.000000,0.1520,0.805,129.875,4,forro,2.831667